services:
  gitea:
    image: gitea/gitea:1.27.3
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__ROOT_URL=http://localhost:3000/
    ports:
      - "3000:3000"